### ISSUE TITLE
Unplanned orders - scheduled date and sequence

### ISSUE THREAD

**Issue by oscarfabiano** [valor-distributions/cvlweb#2]
1 ) It's not saving the scheduled date. I choose March 16 and it's showing March 6 on "planned" tab.
2 ) It's saving sequence 1 to all orders (planned tab). When back to "unplanned" the system re-order everything again

**Comment by gfernandez-me** [comment]
1) could you say the id from the production order, I need to take a look on the DB
2) i will take a look at this

**Comment by gfernandez-me** [comment]
solved on https://github.com/valor-distributions/cvlweb/commit/4d9d3cee89347ba71b52e5db1db199b81118dbda
