### ISSUE TITLE
Batching - Print option uneven

### ISSUE THREAD

**Issue by oscarfabiano** [valor-distributions/cvlweb#3]
1 ) When starting batching, if we choose the "Print" option is displaying uneven the print preview
![Screenshot from 2020-03-16 17-49-03](https://user-images.githubusercontent.com/34660442/76803166-8b2ad800-67af-11ea-8554-7f3bb1fe4c3d.png)

**Comment by gfernandez-me** [comment]
Could you test again and open the [More settings] option?
See how mine is
![issue github print](https://user-images.githubusercontent.com/5313969/76979095-e5da4600-690d-11ea-82e9-921fb27e5d1c.png)
